### ISSUE TITLE
unfold is much slow

### ISSUE THREAD

**Issue by jiequancui** [wang-chen/kervolution#1]
Hi, I find the nn.unfold is much slow in pytorch. And your implementation is based on nn.unfold.  I want to know if you have any tricks to speed up it ?

**Comment by wang-chen** [comment]
Hi, only the polynomial kernel can be accelerated using pytorch Conv2D directly.
For other kernels, we can write cuda extensions, such as [this page](https://pytorch.org/tutorials/advanced/cpp_extension.html)

**Comment by jiequancui** [comment]
Very Thanks
