### ISSUE TITLE
Excessive GPU memory consumption.

### ISSUE THREAD

**Issue by Sumching** [wang-chen/kervolution#2]
Hi, 
I got much insight from your amazing work.
But it cost too much memory because the operator `F.unflod`. 
It will almost consume 9 times memory if the kernel size is (3, 3).
Is there any way that implements KERV with little memory consumption?

**Comment by wang-chen** [comment]
Please refer to this closed [issue](https://github.com/wang-chen/kervolution/issues/1#issuecomment-692439750).
