### ISSUE TITLE
Confusion as to the Nonlinear order terms

### ISSUE THREAD

**Issue by tolusophy** [wang-chen/kervolution#6]
What is the difference between the Kerv2D polynomial kernel with a degree of 2, balance of 1 and Conv2D kernel which is followed by an activation layer of x^2?

**Comment by wang-chen** [comment]
I guess you mean the polynomial kernel with a degree of 2 and a balance of 0, i.e., (x^w + 0)^2, then it is equivalent to Conv2D followed by an activation layer of $\cdot^2$. This is also the point that kervolutional networks try to subsume convolutional networks and provide more expressive representation capabilities.

**Comment by tolusophy** [comment]
Thank you for the clarification
